dataset:
  name: PDE_KS
  pair_id:
  - 3
model:
  name: DMD_bagopt
  train_split: 0.75   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
  seed: 0
  n_trials: 10
  method: bagopt
hyperparameters: # Specify hyperparameters and ranges
  rank:
    type: randint
    lower_bound: 10
    upper_bound: 50
  delay:
    type: choice
    choices: [5, 10]
  eig_constraints:
    type: choice
    choices: [['stable'], ['conjugate_pairs'], ['stable', 'conjugate_pairs']]
