dataset:
  name: PDE_KS
  pair_id:
  - 1
hyperparameters:
  rank:
    lower_bound: 30
    type: randint
    upper_bound: 80
model:
  method: classic
  n_trials: 5
  name: DMD_classic
  seed: 0
  train_split: 0.75
