dataset:
  name: ODE_Lorenz
  pair_id: 
  - 8
  - 9
model:
  name: DMD_classic
  train_split: 0.75   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
  seed: 0
  n_trials: 10
  method: classic
hyperparameters: # Specify hyperparameters and ranges
  rank:
    type: randint
    lower_bound: 3
    upper_bound: 10
  parametric:
    type: choice
    choices: [monolithic, partitioned]
