dataset:
  name: PDE_KS
  pair_id:
  - 3
hyperparameters:
  rank:
    lower_bound: 20
    type: randint
    upper_bound: 60
model:
  method: classic
  n_trials: 5
  name: DMD_classic
  seed: 0
  train_split: 0.75
