dataset:
  name: PDE_KS
  pair_id:
  - 8
hyperparameters:
  parametric:
    choices:
    - monolithic
    - partitioned
    type: choice
  rank:
    lower_bound: 10
    type: randint
    upper_bound: 50
model:
  method: classic
  n_trials: 10
  name: DMD_classic
  seed: 0
  train_split: 0.75
