dataset:
  name: PDE_KS
  pair_id:
  - 2
hyperparameters:
  rank:
    lower_bound: 30
    type: randint
    upper_bound: 60
model:
  method: classic
  n_trials: 10
  name: DMD_classic
  seed: 0
  train_split: 0.75
