dataset:
  name: PDE_KS
  pair_id:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
model:
  delay: 10
  eig_constraints:
  - stable
  method: bagopt
  name: DMD
  rank: 11
  seed: 0
  parametric: monolithic