dataset:
  name: PDE_KS
  pair_id:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
model:
  delay: 30
  method: hankel
  name: DMD
  rank: 123
  seed: 0
  parametric: monolithic # monolithic or partitioned