dataset:
  name: ODE_Lorenz
  # pair_id: [8,9]
model:
  name: DMD
  method: bagopt
  rank: 10
  num_trials: 0
  # eig_constraints: 
  #   - 'conjugate_pairs'
  #   - 'stable'
  delay: 40
  parametric: monolithic # monolithic or partitioned