dataset:
  name: PDE_KS
  pair_id:
  - 1
hyperparameters:
  rank:
    lower_bound: 30
    type: randint
    upper_bound: 80
  delay:
    type: choice
    choices: [10, 20, 30]
model:
  method: highorder
  n_trials: 5
  name: DMD_highorder
  seed: 0
  train_split: 0.75