dataset:
  name: PDE_KS
  pair_id:
  - 9
hyperparameters:
  parametric:
    choices:
    - monolithic
    - partitioned
    type: choice
  rank:
    lower_bound: 20
    type: randint
    upper_bound: 80
  delay:
    type: choice
    choices: [10, 20, 30]
model:
  method: highorder
  n_trials: 10
  name: DMD_highorder
  seed: 0
  train_split: 0.75
