dataset:
  name: ODE_Lorenz
  pair_id:
  - 4
hyperparameters:
  rank:
    lower_bound: 3
    type: randint
    upper_bound: 20
  delay:
    type: choice
    choices: [10, 25, 50, 75, 100]
model:
  method: highorder
  n_trials: 10
  name: DMD_highorder
  seed: 0
  train_split: 0.75