dataset:
  name: ODE_Lorenz
  pair_id:
  - 6
hyperparameters:
  rank:
    lower_bound: 3
    type: randint
    upper_bound: 20
  delay:
    type: choice
    choices: [10, 20, 30]
model:
  method: hankel
  n_trials: 5
  name: DMD_hankel
  seed: 0
  train_split: 0.75