dataset:
  name: PDE_KS
  pair_id:
  - 6
hyperparameters:
  rank:
    lower_bound: 10
    type: randint
    upper_bound: 50
  delay:
    type: choice
    choices: [10, 20, 30]
model:
  method: hankel
  n_trials: 10
  name: DMD_hankel
  seed: 0
  train_split: 0.75
